# Neural Network for Predicting World Series Champions
The procedure has been borrowed in part from the machine learning class examples

# Read in data and pre-process

In [1]:
# import dependencies
import pandas as pd
import warnings
import numpy as np
warnings.filterwarnings('ignore')

In [2]:
# read in data
pd.set_option('display.max_columns', None)
mlb_df = pd.read_csv('resources/mlb_data.csv')
# mlb_df.head()

In [3]:
# change the League column to be binary instead of string
for i, row in mlb_df.iterrows():
#     print(i,row['Lg'])
    if row['Lg'] == 'AL':
        mlb_df.at[i,'Lg'] = 0
#         print(f'new value at {i} is {mlb_df.at[i,"Lg"]}')
    elif row['Lg'] == 'NL':
        mlb_df.at[i,'Lg'] = 1
#         print(f'new value at {i} is {mlb_df.at[i,"Lg"]}')

In [4]:
# league is now a 1 or 0
# mlb_df.head()
# mlb_df.dtypes

# Split into training and testing set
Manually split the data by season. Odd years will be used for training, while even years will be used for testing

In [5]:
# get X and Y train for making the model
train_df = mlb_df.loc[mlb_df['Year'] % 2 == 1]
train_data = train_df.values
X_train = train_data[:, 3:22]
y_train = train_data[:,23]

In [6]:
# get X and Y for making the model
test_df = mlb_df.loc[mlb_df['Year'] % 2 == 0]
test_data = test_df.values
X_test = test_data[:, 3:22]
y_test = test_data[:,23]

# Scaling and One-hot encoding

In [7]:
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)

In [8]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [9]:
# label encode the winner column
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
label_encoder.fit(y_test)
encoded_y_test = label_encoder.transform(y_test)

In [10]:
# One-hot encoding
from keras.utils import to_categorical

y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)
# y_train_categorical

Using TensorFlow backend.

# Create model

In [11]:
from tensorflow.keras.models import Sequential

model = Sequential()

In [12]:
X_train.shape

(300, 19)

In [13]:
from tensorflow.keras.layers import Dense
number_inputs = 19
number_hidden_nodes = 4
model.add(Dense(units=number_hidden_nodes, activation='relu', input_dim=number_inputs))
model.add(Dense(4))

WARNING:tensorflow:From C:\Users\Owner\anaconda3\envs\PythonData\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor

In [14]:
number_classes = 2
model.add(Dense(units=number_classes, activation='softmax'))

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 4)                 80
_________________________________________________________________
dense_1 (Dense)              (None, 4)                 20
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 10
=================================================================
Total params: 110
Trainable params: 110
Non-trainable params: 0
_________________________________________________________________

In [16]:
# # Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [17]:
print(X_train_scaled.shape)
print(y_train_categorical.shape)

(300, 19)
(300, 2)

In [18]:
# Fit the model
model.fit(
    x=X_train_scaled,
    y=y_train_categorical,
    epochs=1000,
    shuffle=False,
    verbose=0
)

In [19]:
# Evaluate the model using the testing data
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

330/330 - 0s - loss: 1.2238 - acc: 0.9424
Loss: 1.2238410682389231, Accuracy: 0.9424242377281189

In [20]:
encoded_predictions = model.predict_classes(X_test_scaled)
prediction_labels = label_encoder.inverse_transform(encoded_predictions)
# print(f"Predicted classes: {prediction_labels}")
# print(f"Actual Labels: {list(y_test)}")

# Post-process and analyze results

In [21]:
pd.set_option('display.max_rows', None)
predictions_df = pd.DataFrame({'Prediction':prediction_labels, 'Actual':list(y_test)})
# predictions_df.head()

In [22]:
winners_df = predictions_df.loc[predictions_df['Actual']]
# winners_df

In [23]:
# connect predictions to the team and season using iloc and test_df
teams = []
years = []
for i, row in winners_df.iterrows():
    team = test_df.iloc[i,2]
    year = test_df.iloc[i,1]
    teams.append(team)
    years.append(year)

In [24]:
# display predictions by team
winners_df['Team'] = teams
winners_df['Year'] = years
# winners_df

In [25]:
# using probabilities 
probs = model.predict_proba(X_test_scaled)
# probs

In [26]:
# dataframe cleanup
probs_df = pd.DataFrame.from_records(probs)
probs_df[0] = probs_df[0] * 100
probs_df[1] = probs_df[1] * 100
probs_df.rename(columns={0:'False', 1:'True'}, inplace=True)
# probs_df.head()

In [27]:
# connect predictions to the team and season using iloc and test_df
all_teams = []
all_years = []
for i, row in probs_df.iterrows():
    team = test_df.iloc[i,2]
    year = test_df.iloc[i,1]
    all_teams.append(team)
    all_years.append(year)
# print(all_years)

In [28]:
# add teams to dataframe
probs_df['Year'] = all_years
probs_df['Team'] = all_teams
probs_df.sort_values(by=['Year','True'],ascending=False)
# probs_df.head()

          False          True  Year Team
285  100.000000  5.091336e-21  2020  LAD
313  100.000000  1.236524e-26  2020  TBR
317  100.000000  3.548343e-33  2020  OAK
326  100.000000  2.741340e-33  2020  CLE
301  100.000000  8.436959e-35  2020  SDP
329  100.000000  7.766978e-35  2020  STL
305  100.000000  6.810755e-35  2020  MIN
316  100.000000  1.424783e-35  2020  CHC
297  100.000000  0.000000e+00  2020  ATL
300  100.000000  0.000000e+00  2020  CHW
303  100.000000  0.000000e+00  2020  NYY
306  100.000000  0.000000e+00  2020  CIN
307  100.000000  0.000000e+00  2020  TOR
308  100.000000  0.000000e+00  2020  NYM
309  100.000000  0.000000e+00  2020  LAA
310  100.000000  0.000000e+00  2020  PHI
311  100.000000  0.000000e+00  2020  BOS
312  100.000000  0.000000e+00  2020  SFG
314  100.000000  0.000000e+00  2020  BAL
315  100.000000  0.000000e+00  2020  MIL
318  100.000000  0.000000e+00  2020  HOU
319  100.000000  0.000000e+00  2020  KCR
320  100.000000  0.000000e+00  2020  WSN
321  100.000000  0.000000e+00  2020  COL
322  100.000000  0.000000e+00  2020  DET
323  100.000000  0.000000e+00  2020  TEX
324  100.000000  0.000000e+00  2020  MIA
325  100.000000  0.000000e+00  2020  SEA
327  100.000000  0.000000e+00  2020  PIT
328  100.000000  0.000000e+00  2020  ARI
48    41.166693  5.883331e+01  2018  BOS
31    99.980623  1.938522e-02  2018  CLE
46   100.000000  6.295234e-12  2018  COL
86   100.000000  2.035197e-16  2018  WSN
191  100.000000  1.268594e-17  2018  PIT
128  100.000000  6.180366e-19  2018  SEA
0    100.000000  4.417174e-21  2018  NYY
26   100.000000  1.449844e-21  2018  MIL
51   100.000000  5.420875e-22  2018  HOU
129  100.000000  5.766066e-23  2018  ATL
156  100.000000  8.764770e-24  2018  MIN
214  100.000000  8.519836e-24  2018  TBR
16   100.000000  3.316721e-24  2018  OAK
37   100.000000  9.973467e-25  2018  LAA
11   100.000000  6.373979e-25  2018  LAD
52   100.000000  9.825937e-30  2018  STL
138  100.000000  3.433606e-30  2018  CIN
151  100.000000  2.580924e-34  2018  CHC
28   100.000000  2.273082e-35  2018  TOR
79   100.000000  0.000000e+00  2018  TEX
92   100.000000  0.000000e+00  2018  BAL
98   100.000000  0.000000e+00  2018  PHI
110  100.000000  0.000000e+00  2018  CHW
127  100.000000  0.000000e+00  2018  ARI
144  100.000000  0.000000e+00  2018  NYM
172  100.000000  0.000000e+00  2018  SDP
197  100.000000  0.000000e+00  2018  KCR
250  100.000000  0.000000e+00  2018  DET
254  100.000000  0.000000e+00  2018  SFG
264  100.000000  0.000000e+00  2018  MIA
49    41.166693  5.883331e+01  2016  BOS
100   93.731755  6.268242e+00  2016  CLE
20   100.000000  8.341186e-11  2016  SEA
41   100.000000  8.229535e-12  2016  DET
35   100.000000  5.877009e-16  2016  TEX
56   100.000000  1.690091e-17  2016  WSN
19   100.000000  8.310698e-18  2016  STL
204  100.000000  3.515708e-19  2016  PIT
265  100.000000  1.776651e-20  2016  MIA
224  100.000000  1.133348e-20  2016  KCR
149  100.000000  5.705178e-22  2016  CHW
71   100.000000  1.228065e-22  2016  HOU
195  100.000000  4.340432e-24  2016  LAA
106  100.000000  7.181204e-26  2016  NYY
24   100.000000  1.113281e-27  2016  TOR
262  100.000000  9.236118e-28  2016  SFG
55   100.000000  7.577568e-28  2016  COL
2    100.000000  2.934222e-29  2016  BAL
80   100.000000  1.852653e-29  2016  MIL
279  100.000000  8.764705e-31  2016  ATL
88   100.000000  7.517035e-32  2016  ARI
165  100.000000  2.299678e-32  2016  CIN
69   100.000000  3.856685e-35  2016  CHC
146  100.000000  2.016367e-36  2016  OAK
27   100.000000  0.000000e+00  2016  NYM
32   100.000000  0.000000e+00  2016  TBR
63   100.000000  0.000000e+00  2016  MIN
90   100.000000  0.000000e+00  2016  LAD
121  100.000000  0.000000e+00  2016  SDP
178  100.000000  0.000000e+00  2016  PHI
199  100.000000  1.808845e-07  2014  DET
122  100.000000  2.665189e-08  2014  TOR
253  100.000000  1.145773e-17  2014  LAD
302  100.000000  1.701038e-20  2014  KCR
200  100.000000  3.967843e-22  2014  LAA
215  100.000000  1.427571e-24  2014  MIL
196  100.000000  1.770758e-27  2014  PIT
42   100.000000  9.069261e-29  2014  BAL
291  100.000000  2.061198e-32  2014  TEX
266  100.000000  1.660204e-32  2014  MIN
198  100.000000  8.394327e-35  2014  CHW
233  100.000000  4.362269e-35  2014  CLE
99   100.000000  0.000000e+00  2014  COL
169  100.000000  0.000000e+00  2014  HOU
192  100.000000  0.000000e+00  2014  CHC
207  100.000000  0.000000e+00  2014  WSN
225  100.000000  0.000000e+00  2014  NYY
226  100.000000  0.000000e+00  2014  OAK
246  100.000000  0.000000e+00  2014  SEA
257  100.000000  0.000000e+00  2014  SFG
259  100.000000  0.000000e+00  2014  CIN
271  100.000000  0.000000e+00  2014  NYM
272  100.000000  0.000000e+00  2014  PHI
277  100.000000  0.000000e+00  2014  ATL
278  100.000000  0.000000e+00  2014  BOS
280  100.000000  0.000000e+00  2014  MIA
286  100.000000  0.000000e+00  2014  ARI
287  100.000000  0.000000e+00  2014  TBR
293  100.000000  0.000000e+00  2014  SDP
296  100.000000  0.000000e+00  2014  STL
64    48.567781  5.143222e+01  2012  TEX
170   99.161834  8.381655e-01  2012  DET
4     99.355257  6.447437e-01  2012  NYY
43    99.999976  2.132042e-05  2012  CHW
59    99.999988  1.519094e-05  2012  MIL
94   100.000000  1.006010e-07  2012  LAA
186  100.000000  3.843019e-09  2012  STL
160  100.000000  5.695732e-10  2012  ARI
298  100.000000  2.155659e-14  2012  SFG
190  100.000000  4.618543e-20  2012  PHI
81   100.000000  7.854235e-23  2012  WSN
260  100.000000  1.383391e-23  2012  KCR
247  100.000000  9.550607e-25  2012  CLE
161  100.000000  2.695003e-25  2012  BOS
72   100.000000  5.315853e-26  2012  TOR
38   100.000000  6.646366e-27  2012  BAL
261  100.000000  1.176100e-29  2012  MIN
281  100.000000  6.112891e-32  2012  SDP
139  100.000000  9.618931e-35  2012  CIN
239  100.000000  7.140443e-35  2012  NYM
78   100.000000  0.000000e+00  2012  OAK
130  100.000000  0.000000e+00  2012  TBR
145  100.000000  0.000000e+00  2012  PIT
157  100.000000  0.000000e+00  2012  COL
219  100.000000  0.000000e+00  2012  ATL
220  100.000000  0.000000e+00  2012  SEA
227  100.000000  0.000000e+00  2012  HOU
243  100.000000  0.000000e+00  2012  CHC
244  100.000000  0.000000e+00  2012  MIA
289  100.000000  0.000000e+00  2012  LAD
234   41.166693  5.883331e+01  2010  MIN
61    54.045069  4.595492e+01  2010  NYY
174   78.680307  2.131969e+01  2010  TEX
44    99.310172  6.898309e-01  2010  BOS
93    99.999928  7.250961e-05  2010  CIN
123  100.000000  5.368335e-08  2010  CHW
111  100.000000  6.729012e-11  2010  MIL
135  100.000000  1.371095e-12  2010  COL
208  100.000000  4.993910e-13  2010  DET
158  100.000000  1.667205e-16  2010  PHI
216  100.000000  1.809802e-17  2010  STL
201  100.000000  7.808361e-20  2010  LAA
1    100.000000  7.032637e-20  2010  TOR
173  100.000000  1.522375e-23  2010  SFG
181  100.000000  1.495579e-24  2010  TBR
221  100.000000  1.875411e-25  2010  CHC
294  100.000000  2.981771e-29  2010  OAK
209  100.000000  2.041458e-29  2010  FLA
222  100.000000  9.336104e-31  2010  WSN
282  100.000000  1.559958e-31  2010  KCR
268  100.000000  3.190109e-32  2010  NYM
240  100.000000  1.284719e-32  2010  ATL
113  100.000000  4.659651e-35  2010  ARI
255  100.000000  0.000000e+00  2010  BAL
258  100.000000  0.000000e+00  2010  SDP
267  100.000000  0.000000e+00  2010  CLE
269  100.000000  0.000000e+00  2010  PIT
283  100.000000  0.000000e+00  2010  LAD
295  100.000000  0.000000e+00  2010  HOU
299  100.000000  0.000000e+00  2010  SEA
136   41.166693  5.883331e+01  2008  BOS
188   62.915790  3.708421e+01  2008  LAA
141   99.888891  1.111117e-01  2008  NYM
39    99.974114  2.589049e-02  2008  PHI
102   99.997842  2.156891e-03  2008  CHC
114   99.999487  5.080369e-04  2008  NYY
12   100.000000  6.387742e-07  2008  CHW
73   100.000000  1.419941e-08  2008  MIL
292  100.000000  4.588871e-09  2008  MIN
143  100.000000  6.609862e-10  2008  CLE
263  100.000000  2.586929e-10  2008  ATL
152  100.000000  1.309652e-10  2008  HOU
133  100.000000  1.719329e-11  2008  STL
115  100.000000  1.194962e-15  2008  TBR
50   100.000000  4.650070e-17  2008  FLA
270  100.000000  3.359901e-18  2008  TOR
245  100.000000  1.926296e-18  2008  LAD
182  100.000000  1.000737e-20  2008  COL
284  100.000000  4.675139e-21  2008  KCR
95   100.000000  2.397591e-23  2008  CIN
304  100.000000  3.292291e-24  2008  SFG
65   100.000000  1.510018e-27  2008  DET
187  100.000000  2.086104e-28  2008  ARI
205  100.000000  2.812265e-33  2008  PIT
140  100.000000  6.242752e-35  2008  BAL
82   100.000000  0.000000e+00  2008  TEX
203  100.000000  0.000000e+00  2008  SDP
273  100.000000  0.000000e+00  2008  OAK
274  100.000000  0.000000e+00  2008  SEA
288  100.000000  0.000000e+00  2008  WSN
66    41.166693  5.883331e+01  2006  NYM
232   94.078815  5.921188e+00  2006  MIN
189   99.950671  4.932553e-02  2006  LAA
206   99.999428  5.666217e-04  2006  LAD
131   99.999952  4.247420e-05  2006  OAK
47   100.000000  2.053103e-06  2006  NYY
84   100.000000  1.180569e-06  2006  BOS
33   100.000000  5.023298e-08  2006  PHI
57   100.000000  2.039807e-08  2006  DET
179  100.000000  1.923104e-09  2006  SDP
183  100.000000  6.453651e-11  2006  ARI
103  100.000000  9.136932e-12  2006  STL
171  100.000000  1.360134e-12  2006  SFG
29   100.000000  9.593419e-14  2006  CIN
116  100.000000  5.756790e-16  2006  MIL
193  100.000000  8.795108e-18  2006  COL
112  100.000000  3.536465e-18  2006  FLA
134  100.000000  1.539860e-18  2006  HOU
70   100.000000  2.347459e-19  2006  TOR
9    100.000000  6.908858e-20  2006  CHW
167  100.000000  1.821733e-21  2006  WSN
142  100.000000  4.444127e-23  2006  SEA
22   100.000000  2.702542e-23  2006  ATL
107  100.000000  6.906917e-25  2006  TEX
77   100.000000  1.220571e-26  2006  CLE
159  100.000000  4.575754e-27  2006  CHC
237  100.000000  2.478704e-32  2006  PIT
89   100.000000  0.000000e+00  2006  TBD
166  100.000000  0.000000e+00  2006  BAL
275  100.000000  0.000000e+00  2006  KCR
23    41.166693  5.883331e+01  2004  BOS
40    41.166693  5.883331e+01  2004  STL
96    41.166693  5.883331e+01  2004  HOU
108   41.166693  5.883331e+01  2004  SFG
7     92.924839  7.075159e+00  2004  NYY
13    98.307002  1.692999e+00  2004  CHC
241   98.515409  1.484592e+00  2004  SDP
87    99.919981  8.002609e-02  2004  MIN
223   99.986243  1.375482e-02  2004  FLA
36    99.997652  2.353066e-03  2004  PHI
91    99.998426  1.577564e-03  2004  OAK
58    99.999118  8.867675e-04  2004  LAD
119  100.000000  5.631628e-07  2004  ATL
175  100.000000  7.887928e-11  2004  ANA
104  100.000000  4.566653e-19  2004  CLE
147  100.000000  3.188779e-19  2004  BAL
17   100.000000  1.342463e-20  2004  TEX
235  100.000000  6.340326e-23  2004  PIT
83   100.000000  9.987125e-27  2004  CIN
229  100.000000  2.765823e-27  2004  TBD
101  100.000000  1.882318e-27  2004  NYM
213  100.000000  1.068009e-28  2004  MON
230  100.000000  3.647465e-29  2004  TOR
248  100.000000  3.629680e-32  2004  SEA
62   100.000000  1.645388e-32  2004  DET
6    100.000000  4.440188e-34  2004  CHW
60   100.000000  0.000000e+00  2004  COL
217  100.000000  0.000000e+00  2004  KCR
251  100.000000  0.000000e+00  2004  ARI
252  100.000000  0.000000e+00  2004  MIL
21    41.166693  5.883331e+01  2002  NYY
124   41.166693  5.883331e+01  2002  BOS
210   41.166693  5.883331e+01  2002  ANA
212   99.834049  1.659438e-01  2002  SEA
132   99.988043  1.196047e-02  2002  STL
202   99.996364  3.634010e-03  2002  LAD
154  100.000000  1.448997e-07  2002  MIN
176  100.000000  1.252759e-07  2002  MON
162  100.000000  9.050590e-08  2002  ARI
74   100.000000  1.829126e-09  2002  SFG
53   100.000000  8.207072e-12  2002  OAK
153  100.000000  5.327533e-12  2002  HOU
164  100.000000  1.295070e-12  2002  PHI
228  100.000000  1.279341e-14  2002  FLA
184  100.000000  7.508384e-16  2002  NYM
30   100.000000  1.934567e-17  2002  CHW
85   100.000000  1.871021e-20  2002  CLE
97   100.000000  1.838433e-20  2002  TOR
148  100.000000  1.080116e-20  2002  CIN
249  100.000000  2.004639e-30  2002  SDP
67   100.000000  1.646834e-30  2002  CHC
168  100.000000  1.005346e-30  2002  ATL
211  100.000000  8.809882e-33  2002  COL
15   100.000000  3.414176e-35  2002  TEX
163  100.000000  5.421457e-36  2002  BAL
236  100.000000  3.002408e-36  2002  PIT
238  100.000000  0.000000e+00  2002  KCR
242  100.000000  0.000000e+00  2002  MIL
256  100.000000  0.000000e+00  2002  TBD
276  100.000000  0.000000e+00  2002  DET
76    41.166693  5.883331e+01  2000  SEA
118   58.026844  4.197316e+01  2000  ATL
14    60.943323  3.905668e+01  2000  STL
117   98.727113  1.272889e+00  2000  ARI
18    99.351174  6.488266e-01  2000  SFG
45    99.990857  9.143844e-03  2000  LAD
75    99.999940  5.474127e-05  2000  NYM
155   99.999964  3.525557e-05  2000  BOS
8     99.999988  1.091723e-05  2000  OAK
54   100.000000  1.440339e-11  2000  NYY
68   100.000000  4.075866e-12  2000  CIN
194  100.000000  1.376130e-13  2000  SDP
25   100.000000  1.706397e-16  2000  CLE
185  100.000000  2.309710e-17  2000  FLA
34   100.000000  2.178469e-19  2000  CHW
150  100.000000  1.901884e-21  2000  PIT
125  100.000000  1.487065e-22  2000  DET
231  100.000000  4.769289e-23  2000  PHI
109  100.000000  1.538635e-23  2000  CHC
177  100.000000  1.088691e-28  2000  TBD
180  100.000000  5.967993e-29  2000  COL
126  100.000000  2.360403e-30  2000  MIL
105  100.000000  1.451624e-31  2000  BAL
10   100.000000  2.473705e-33  2000  ANA
290  100.000000  1.369600e-34  2000  MIN
5    100.000000  5.252033e-35  2000  TOR
3    100.000000  1.731752e-35  2000  HOU
218  100.000000  2.667342e-36  2000  KCR
120  100.000000  0.000000e+00  2000  MON
137  100.000000  0.000000e+00  2000  TEX

In [29]:
# add top three most likely teams for each season to a dictionary
seasons = probs_df['Year'].unique()
top_three = {}
for season in seasons:
    df = probs_df.loc[probs_df['Year'] == season]
    df = df.sort_values(by='True', ascending=False)
    top_three[season] = {'first_prediction':df.iloc[0,3], 'second_prediction': df.iloc[1,3], 'third_prediction': df.iloc[2,3]}

In [30]:
# put dictionary into dataframe
top_three_df = pd.DataFrame(top_three)
top_three_df = top_three_df.transpose()

In [31]:
# sort by year
top_three_df = top_three_df.sort_index()

In [32]:
# adding year as a column
top_three_df.reset_index(inplace=True)
top_three_df = top_three_df.rename(columns={'index':'Year'})

In [33]:
# top_three_df

In [34]:
# bring in actual winners
even_df = top_three_df.merge(winners_df, on='Year')

In [35]:
# dataframe cleanup
even_df.drop(columns=['Prediction','Actual'], inplace=True)

In [36]:
even_df.head()

   Year first_prediction second_prediction third_prediction Team
0  2000              SEA               ATL              STL  NYY
1  2002              ANA               NYY              BOS  ANA
2  2004              BOS               STL              SFG  BOS
3  2006              NYM               MIN              LAA  STL
4  2008              BOS               LAA              NYM  PHI

In [37]:
even_df.rename(columns={'Team':'actual'}, inplace=True)

In [38]:
even_df.head()

   Year first_prediction second_prediction third_prediction actual
0  2000              SEA               ATL              STL    NYY
1  2002              ANA               NYY              BOS    ANA
2  2004              BOS               STL              SFG    BOS
3  2006              NYM               MIN              LAA    STL
4  2008              BOS               LAA              NYM    PHI

# Part 2 - Repeat for odd years

In [39]:
# import dependencies
import pandas as pd
import warnings
import numpy as np
warnings.filterwarnings('ignore')

In [40]:
# read in data
pd.set_option('display.max_columns', None)
mlb_df = pd.read_csv('resources/mlb_data.csv')
# mlb_df.head()

In [41]:
# change the League column to be binary instead of string
for i, row in mlb_df.iterrows():
#     print(i,row['Lg'])
    if row['Lg'] == 'AL':
        mlb_df.at[i,'Lg'] = 0
#         print(f'new value at {i} is {mlb_df.at[i,"Lg"]}')
    elif row['Lg'] == 'NL':
        mlb_df.at[i,'Lg'] = 1
#         print(f'new value at {i} is {mlb_df.at[i,"Lg"]}')

In [42]:
# league is now a 1 or 0
# mlb_df.head()
# mlb_df.dtypes

# Split into training and testing set
Manually split the data by season. Even years will be used for training, while odd years will be used for testing

In [43]:
# get X and Y train for making the model
train_df = mlb_df.loc[mlb_df['Year'] % 2 == 0]
train_data = train_df.values
X_train = train_data[:, 3:22]
y_train = train_data[:,23]

In [44]:
# get X and Y for making the model
test_df = mlb_df.loc[mlb_df['Year'] % 2 == 1]
test_data = test_df.values
X_test = test_data[:, 3:22]
y_test = test_data[:,23]

# Scaling and One-hot encoding

In [45]:
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)

In [46]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [47]:
# label encode the winner column
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
label_encoder.fit(y_test)
encoded_y_test = label_encoder.transform(y_test)

In [48]:
# One-hot encoding
from keras.utils import to_categorical

y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)
# y_train_categorical

# Create model

In [49]:
from tensorflow.keras.models import Sequential

model = Sequential()

In [50]:
X_train.shape

(330, 19)

In [51]:
from tensorflow.keras.layers import Dense
number_inputs = 19
number_hidden_nodes = 4
model.add(Dense(units=number_hidden_nodes, activation='relu', input_dim=number_inputs))
model.add(Dense(4))

In [52]:
number_classes = 2
model.add(Dense(units=number_classes, activation='softmax'))

In [53]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_3 (Dense)              (None, 4)                 80
_________________________________________________________________
dense_4 (Dense)              (None, 4)                 20
_________________________________________________________________
dense_5 (Dense)              (None, 2)                 10
=================================================================
Total params: 110
Trainable params: 110
Non-trainable params: 0
_________________________________________________________________

In [54]:
# # Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [55]:
print(X_train_scaled.shape)
print(y_train_categorical.shape)

(330, 19)
(330, 2)

In [56]:
# Fit the model
model.fit(
    x=X_train_scaled,
    y=y_train_categorical,
    epochs=1000,
    shuffle=False,
    verbose=0
)

In [57]:
# Evaluate the model using the testing data
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

300/300 - 0s - loss: 1.0833 - acc: 0.9400
Loss: 1.0833356810268016, Accuracy: 0.9399999976158142

In [58]:
encoded_predictions = model.predict_classes(X_test_scaled)
prediction_labels = label_encoder.inverse_transform(encoded_predictions)
# print(f"Predicted classes: {prediction_labels}")
# print(f"Actual Labels: {list(y_test)}")

# Post-process and analyze results

In [59]:
pd.set_option('display.max_rows', None)
predictions_df = pd.DataFrame({'Prediction':prediction_labels, 'Actual':list(y_test)})
# predictions_df.head()

In [60]:
winners_df = predictions_df.loc[predictions_df['Actual']]
# winners_df

In [61]:
# connect predictions to the team and season using iloc and test_df
teams = []
years = []
for i, row in winners_df.iterrows():
    team = test_df.iloc[i,2]
    year = test_df.iloc[i,1]
    teams.append(team)
    years.append(year)

In [62]:
# display predictions by team
winners_df['Team'] = teams
winners_df['Year'] = years
# winners_df

In [63]:
# using probabilities 
probs = model.predict_proba(X_test_scaled)
# probs

In [64]:
# dataframe cleanup
probs_df = pd.DataFrame.from_records(probs)
probs_df[0] = probs_df[0] * 100
probs_df[1] = probs_df[1] * 100
probs_df.rename(columns={0:'False', 1:'True'}, inplace=True)
# probs_df.head()

In [65]:
# connect predictions to the team and season using iloc and test_df
all_teams = []
all_years = []
for i, row in probs_df.iterrows():
    team = test_df.iloc[i,2]
    year = test_df.iloc[i,1]
    all_teams.append(team)
    all_years.append(year)
# print(all_years)

In [66]:
# add teams to dataframe
probs_df['Year'] = all_years
probs_df['Team'] = all_teams
probs_df.sort_values(by=['Year','True'],ascending=False)
# probs_df.head()

          False          True  Year Team
25   100.000000  6.472664e-21  2019  WSN
3    100.000000  1.643790e-22  2019  LAD
2    100.000000  2.019826e-26  2019  HOU
63   100.000000  4.131683e-30  2019  STL
5    100.000000  2.481988e-31  2019  OAK
0    100.000000  9.046191e-34  2019  MIN
1    100.000000  0.000000e+00  2019  NYY
6    100.000000  0.000000e+00  2019  CHC
7    100.000000  0.000000e+00  2019  MIL
8    100.000000  0.000000e+00  2019  ATL
9    100.000000  0.000000e+00  2019  TOR
11   100.000000  0.000000e+00  2019  BOS
13   100.000000  0.000000e+00  2019  NYM
15   100.000000  0.000000e+00  2019  SEA
31   100.000000  0.000000e+00  2019  CIN
32   100.000000  0.000000e+00  2019  COL
37   100.000000  0.000000e+00  2019  CLE
38   100.000000  0.000000e+00  2019  TEX
44   100.000000  0.000000e+00  2019  ARI
45   100.000000  0.000000e+00  2019  LAA
48   100.000000  0.000000e+00  2019  SDP
50   100.000000  0.000000e+00  2019  TBR
52   100.000000  0.000000e+00  2019  PHI
55   100.000000  0.000000e+00  2019  BAL
118  100.000000  0.000000e+00  2019  CHW
160  100.000000  0.000000e+00  2019  SFG
174  100.000000  0.000000e+00  2019  PIT
177  100.000000  0.000000e+00  2019  KCR
221  100.000000  0.000000e+00  2019  DET
232  100.000000  0.000000e+00  2019  MIA
17   100.000000  3.646182e-12  2017  HOU
58   100.000000  3.830643e-21  2017  CLE
43   100.000000  7.263763e-22  2017  LAD
90   100.000000  5.789183e-24  2017  MIA
86   100.000000  4.306110e-25  2017  STL
39   100.000000  2.462689e-26  2017  CHC
53   100.000000  3.313130e-31  2017  WSN
168  100.000000  6.379980e-35  2017  ATL
14   100.000000  0.000000e+00  2017  NYY
19   100.000000  0.000000e+00  2017  TEX
22   100.000000  0.000000e+00  2017  OAK
23   100.000000  0.000000e+00  2017  BAL
30   100.000000  0.000000e+00  2017  TBR
33   100.000000  0.000000e+00  2017  MIL
34   100.000000  0.000000e+00  2017  NYM
40   100.000000  0.000000e+00  2017  TOR
46   100.000000  0.000000e+00  2017  ARI
49   100.000000  0.000000e+00  2017  CIN
70   100.000000  0.000000e+00  2017  MIN
77   100.000000  0.000000e+00  2017  SEA
93   100.000000  0.000000e+00  2017  KCR
94   100.000000  0.000000e+00  2017  COL
101  100.000000  0.000000e+00  2017  SDP
104  100.000000  0.000000e+00  2017  DET
107  100.000000  0.000000e+00  2017  CHW
108  100.000000  0.000000e+00  2017  LAA
138  100.000000  0.000000e+00  2017  PHI
158  100.000000  0.000000e+00  2017  BOS
215  100.000000  0.000000e+00  2017  PIT
269  100.000000  0.000000e+00  2017  SFG
24    98.738688  1.261314e+00  2015  TOR
247   99.921501  7.849239e-02  2015  KCR
255   99.999034  9.646274e-04  2015  SFG
245  100.000000  9.694603e-11  2015  PIT
126  100.000000  1.608146e-21  2015  NYM
252  100.000000  9.401812e-27  2015  STL
205  100.000000  2.021011e-28  2015  ARI
105  100.000000  2.019261e-29  2015  LAD
216  100.000000  2.824158e-31  2015  DET
143  100.000000  6.275545e-32  2015  TEX
283  100.000000  3.214908e-32  2015  MIA
127  100.000000  3.689380e-35  2015  WSN
180  100.000000  3.409802e-35  2015  BOS
149  100.000000  5.491602e-36  2015  CHC
130  100.000000  4.102240e-36  2015  LAA
27   100.000000  0.000000e+00  2015  HOU
51   100.000000  0.000000e+00  2015  BAL
59   100.000000  0.000000e+00  2015  NYY
83   100.000000  0.000000e+00  2015  SEA
109  100.000000  0.000000e+00  2015  COL
161  100.000000  0.000000e+00  2015  CIN
162  100.000000  0.000000e+00  2015  TBR
199  100.000000  0.000000e+00  2015  MIN
225  100.000000  0.000000e+00  2015  SDP
233  100.000000  0.000000e+00  2015  OAK
235  100.000000  0.000000e+00  2015  MIL
242  100.000000  0.000000e+00  2015  CLE
254  100.000000  0.000000e+00  2015  CHW
262  100.000000  0.000000e+00  2015  PHI
295  100.000000  0.000000e+00  2015  ATL
274    0.030058  9.996995e+01  2013  STL
124  100.000000  3.012923e-06  2013  BOS
201  100.000000  4.725112e-12  2013  CIN
181  100.000000  5.518229e-14  2013  PIT
263  100.000000  2.210881e-15  2013  ARI
182  100.000000  1.521504e-16  2013  WSN
291  100.000000  7.318266e-17  2013  SFG
110  100.000000  7.621526e-18  2013  OAK
251  100.000000  6.227414e-19  2013  LAD
132  100.000000  6.388406e-20  2013  TEX
131  100.000000  1.125298e-23  2013  DET
121  100.000000  6.247447e-27  2013  ATL
171  100.000000  8.011387e-28  2013  LAA
150  100.000000  2.042596e-29  2013  CLE
169  100.000000  1.064539e-29  2013  TBR
191  100.000000  1.838568e-33  2013  COL
234  100.000000  1.728718e-33  2013  SDP
60   100.000000  0.000000e+00  2013  BAL
103  100.000000  0.000000e+00  2013  SEA
112  100.000000  0.000000e+00  2013  TOR
144  100.000000  0.000000e+00  2013  CHC
196  100.000000  0.000000e+00  2013  MIL
217  100.000000  0.000000e+00  2013  MIN
226  100.000000  0.000000e+00  2013  CHW
227  100.000000  0.000000e+00  2013  HOU
237  100.000000  0.000000e+00  2013  NYY
246  100.000000  0.000000e+00  2013  PHI
264  100.000000  0.000000e+00  2013  NYM
288  100.000000  0.000000e+00  2013  KCR
296  100.000000  0.000000e+00  2013  MIA
145    0.547368  9.945263e+01  2011  ARI
113   99.977547  2.245165e-02  2011  MIL
156   99.990296  9.705903e-03  2011  DET
73    99.999857  1.454813e-04  2011  BOS
64   100.000000  4.818566e-11  2011  TEX
178  100.000000  1.408645e-13  2011  STL
281  100.000000  6.128825e-14  2011  SFG
202  100.000000  3.155944e-14  2011  LAA
209  100.000000  9.201294e-15  2011  PHI
41   100.000000  2.457888e-15  2011  NYY
116  100.000000  1.100587e-15  2011  CIN
146  100.000000  1.080516e-19  2011  TBR
228  100.000000  8.900359e-22  2011  CHC
267  100.000000  4.769831e-25  2011  KCR
285  100.000000  7.476857e-31  2011  LAD
140  100.000000  3.919772e-32  2011  ATL
95   100.000000  0.000000e+00  2011  BAL
111  100.000000  0.000000e+00  2011  TOR
175  100.000000  0.000000e+00  2011  COL
206  100.000000  0.000000e+00  2011  CHW
207  100.000000  0.000000e+00  2011  CLE
208  100.000000  0.000000e+00  2011  WSN
222  100.000000  0.000000e+00  2011  FLA
287  100.000000  0.000000e+00  2011  OAK
289  100.000000  0.000000e+00  2011  SEA
290  100.000000  0.000000e+00  2011  NYM
292  100.000000  0.000000e+00  2011  PIT
293  100.000000  0.000000e+00  2011  MIN
297  100.000000  0.000000e+00  2011  HOU
299  100.000000  0.000000e+00  2011  SDP
142   14.705989  8.529401e+01  2009  LAA
190   99.995124  4.881298e-03  2009  STL
192   99.995172  4.825454e-03  2009  FLA
35    99.999332  6.716662e-04  2009  PHI
12   100.000000  2.191545e-06  2009  NYY
236  100.000000  4.923596e-07  2009  LAD
98   100.000000  3.729227e-08  2009  COL
119  100.000000  2.496522e-12  2009  MIL
147  100.000000  2.951814e-14  2009  MIN
61   100.000000  3.280503e-19  2009  BOS
183  100.000000  5.774518e-23  2009  CHC
223  100.000000  7.387348e-25  2009  ATL
280  100.000000  6.543127e-26  2009  SFG
65   100.000000  1.565660e-27  2009  TOR
79   100.000000  1.524278e-34  2009  TBR
36   100.000000  0.000000e+00  2009  TEX
114  100.000000  0.000000e+00  2009  CHW
117  100.000000  0.000000e+00  2009  DET
141  100.000000  0.000000e+00  2009  ARI
184  100.000000  0.000000e+00  2009  CLE
188  100.000000  0.000000e+00  2009  BAL
189  100.000000  0.000000e+00  2009  SEA
193  100.000000  0.000000e+00  2009  CIN
200  100.000000  0.000000e+00  2009  WSN
238  100.000000  0.000000e+00  2009  KCR
240  100.000000  0.000000e+00  2009  HOU
243  100.000000  0.000000e+00  2009  SDP
258  100.000000  0.000000e+00  2009  OAK
275  100.000000  0.000000e+00  2009  PIT
298  100.000000  0.000000e+00  2009  NYM
210   14.918496  8.508151e+01  2007  SEA
152   83.403373  1.659662e+01  2007  COL
128   96.671194  3.328809e+00  2007  DET
56    98.833221  1.166780e+00  2007  PHI
76    99.999726  2.786993e-04  2007  NYY
154  100.000000  2.856891e-06  2007  SDP
133  100.000000  8.076680e-07  2007  ATL
165  100.000000  1.453970e-13  2007  BOS
170  100.000000  2.986778e-15  2007  TOR
218  100.000000  1.254648e-15  2007  CHC
244  100.000000  4.590956e-16  2007  STL
26   100.000000  1.890262e-20  2007  MIL
125  100.000000  3.897191e-21  2007  CLE
278  100.000000  2.741580e-26  2007  LAA
229  100.000000  1.346984e-26  2007  PIT
129  100.000000  1.403164e-28  2007  NYM
123  100.000000  4.534775e-29  2007  TEX
75   100.000000  1.337784e-30  2007  FLA
151  100.000000  5.423412e-32  2007  ARI
72   100.000000  9.921846e-35  2007  CIN
163  100.000000  6.246468e-35  2007  HOU
241  100.000000  3.013620e-35  2007  BAL
99   100.000000  0.000000e+00  2007  CHW
106  100.000000  0.000000e+00  2007  TBD
153  100.000000  0.000000e+00  2007  OAK
260  100.000000  0.000000e+00  2007  SFG
268  100.000000  0.000000e+00  2007  LAD
279  100.000000  0.000000e+00  2007  WSN
284  100.000000  0.000000e+00  2007  MIN
294  100.000000  0.000000e+00  2007  KCR
203    0.000586  9.999942e+01  2005  OAK
115    0.510391  9.948961e+01  2005  ATL
155    0.897097  9.910290e+01  2005  STL
69    99.999976  2.959765e-05  2005  CLE
80   100.000000  3.662924e-09  2005  BOS
137  100.000000  1.919988e-09  2005  NYM
78   100.000000  2.006036e-10  2005  CHW
136  100.000000  1.815477e-12  2005  MIL
29   100.000000  6.463487e-13  2005  NYY
164  100.000000  6.162799e-13  2005  PHI
271  100.000000  3.209501e-19  2005  SFG
102  100.000000  2.552014e-19  2005  BAL
270  100.000000  1.108784e-20  2005  FLA
185  100.000000  8.536729e-22  2005  HOU
286  100.000000  1.249718e-23  2005  WSN
248  100.000000  6.369744e-27  2005  PIT
256  100.000000  4.001196e-27  2005  TOR
230  100.000000  1.119533e-27  2005  LAA
224  100.000000  3.384671e-29  2005  LAD
42   100.000000  1.226633e-29  2005  CIN
4    100.000000  1.410294e-31  2005  TEX
91   100.000000  6.684915e-34  2005  CHC
159  100.000000  2.999412e-34  2005  DET
96   100.000000  0.000000e+00  2005  ARI
197  100.000000  0.000000e+00  2005  TBD
219  100.000000  0.000000e+00  2005  COL
259  100.000000  0.000000e+00  2005  MIN
265  100.000000  0.000000e+00  2005  SDP
266  100.000000  0.000000e+00  2005  SEA
273  100.000000  0.000000e+00  2005  KCR
122   28.705969  7.129403e+01  2003  SFG
97    63.090914  3.690909e+01  2003  HOU
100   84.020203  1.597980e+01  2003  TOR
134   98.250395  1.749604e+00  2003  OAK
88    99.998081  1.922849e-03  2003  STL
204  100.000000  1.111791e-06  2003  MIN
166  100.000000  9.698914e-07  2003  PHI
47   100.000000  6.479720e-09  2003  CHW
249  100.000000  3.709425e-09  2003  SEA
18   100.000000  2.316125e-09  2003  BOS
20   100.000000  2.943767e-11  2003  ATL
198  100.000000  5.982699e-13  2003  FLA
176  100.000000  3.851935e-13  2003  PIT
148  100.000000  3.911725e-15  2003  CHC
84   100.000000  2.524653e-17  2003  COL
179  100.000000  3.265833e-18  2003  KCR
212  100.000000  4.635507e-19  2003  ARI
239  100.000000  4.226309e-30  2003  MON
220  100.000000  1.478955e-33  2003  ANA
276  100.000000  3.411847e-34  2003  LAD
28   100.000000  2.343566e-34  2003  NYY
16   100.000000  0.000000e+00  2003  TEX
87   100.000000  0.000000e+00  2003  MIL
120  100.000000  0.000000e+00  2003  CIN
194  100.000000  0.000000e+00  2003  CLE
211  100.000000  0.000000e+00  2003  DET
213  100.000000  0.000000e+00  2003  BAL
253  100.000000  0.000000e+00  2003  TBD
272  100.000000  0.000000e+00  2003  SDP
277  100.000000  0.000000e+00  2003  NYM
157   97.584981  2.415016e+00  2001  SEA
92    99.613392  3.866143e-01  2001  CHC
62    99.955326  4.466884e-02  2001  CLE
82    99.996436  3.566812e-03  2001  STL
81   100.000000  4.765475e-06  2001  OAK
68   100.000000  3.878907e-08  2001  HOU
71   100.000000  1.411893e-08  2001  LAD
74   100.000000  4.382943e-09  2001  NYY
21   100.000000  3.300545e-10  2001  SFG
67   100.000000  2.147798e-12  2001  ARI
54   100.000000  2.732679e-15  2001  CHW
139  100.000000  8.319075e-17  2001  ATL
167  100.000000  7.627114e-17  2001  FLA
173  100.000000  4.619091e-19  2001  PHI
85   100.000000  2.191685e-23  2001  BOS
172  100.000000  6.805807e-24  2001  MIN
10   100.000000  1.458863e-31  2001  TEX
89   100.000000  7.632949e-36  2001  TOR
57   100.000000  0.000000e+00  2001  COL
66   100.000000  0.000000e+00  2001  MIL
135  100.000000  0.000000e+00  2001  CIN
186  100.000000  0.000000e+00  2001  PIT
187  100.000000  0.000000e+00  2001  SDP
195  100.000000  0.000000e+00  2001  ANA
214  100.000000  0.000000e+00  2001  KCR
231  100.000000  0.000000e+00  2001  NYM
250  100.000000  0.000000e+00  2001  DET
257  100.000000  0.000000e+00  2001  BAL
261  100.000000  0.000000e+00  2001  MON
282  100.000000  0.000000e+00  2001  TBD

In [67]:
# add top three most likely teams for each season to a dictionary
seasons = probs_df['Year'].unique()
top_three = {}
for season in seasons:
    df = probs_df.loc[probs_df['Year'] == season]
    df = df.sort_values(by='True', ascending=False)
    top_three[season] = {'first_prediction':df.iloc[0,3], 'second_prediction': df.iloc[1,3], 'third_prediction': df.iloc[2,3]}

In [68]:
# put dictionary into dataframe
top_three_df = pd.DataFrame(top_three)
top_three_df = top_three_df.transpose()

In [69]:
# sort by year
top_three_df = top_three_df.sort_index()

In [70]:
# adding year as a column
top_three_df.reset_index(inplace=True)
top_three_df = top_three_df.rename(columns={'index':'Year'})

In [71]:
# top_three_df

In [72]:
# bring in actual winners
odd_df = top_three_df.merge(winners_df, on='Year')

In [73]:
# dataframe cleanup
odd_df.drop(columns=['Prediction','Actual'], inplace=True)

In [74]:
odd_df.head()

   Year first_prediction second_prediction third_prediction Team
0  2001              SEA               CHC              CLE  ARI
1  2003              SFG               HOU              TOR  FLA
2  2005              OAK               ATL              STL  CHW
3  2007              SEA               COL              DET  BOS
4  2009              LAA               STL              FLA  NYY

In [75]:
odd_df.rename(columns={'Team':'actual'}, inplace=True)

In [76]:
# odd_df.head()

In [77]:
# even_df.head()

In [78]:
df = pd.concat([even_df, odd_df])
# df.head()

In [79]:
df = df.sort_values(by='Year')
df.reset_index(inplace=True, drop=True)
df.head()

   Year first_prediction second_prediction third_prediction actual
0  2000              SEA               ATL              STL    NYY
1  2001              SEA               CHC              CLE    ARI
2  2002              ANA               NYY              BOS    ANA
3  2003              SFG               HOU              TOR    FLA
4  2004              BOS               STL              SFG    BOS

In [82]:
# add full names to df
teams =  ['ANA','ARI','ATL','BAL','BOS','CHC','CHW','CIN','CLE','COL','DET','FLA','HOU','KCR','LAA','LAD','MIA','MIL','MIN','MON','NYM','NYY','OAK','PHI','PIT','SDP','SEA','SFG','STL','TBD','TBR','TEX','TOR','WSN']
full_names = ['Anahiem Angels','Arizona Diamondbacks','Atlanta Braves','Baltimore Orioles','Boston Red Sox','Chicago Cubs','Chicago White Sox','Cincinnati Reds','Cleveland Indians','Colorado Rockies','Detroit Tigers','Florida Marlins','Houston Astros','Kansas City Royals','Los Angeles Angels','Los Angeles Dodgers','Miami Marlins','Milwaukee Brewers','Minnesota Twins','Montreal Expos','New York Mets','New York Yankees','Oakland Athletics','Philadelphia Phillies','Pittsburgh Pirates','San Diego Padres','Seattle Mariners','San Francisco Giants','St. Louis Cardinals','Tampa Bay Devil Rays','Tampa Bay Rays','Texas Rangers','Toronto Blue Jays','Washington Nationals']
full_names_df = pd.DataFrame({'abbr':teams,'fn':full_names})
# full_names_df

In [85]:
df = df.merge(full_names_df, right_on='abbr', left_on='actual')

In [87]:
df.rename(columns={'fn':'actual_fn'},inplace=True)
df.drop(columns='abbr',inplace=True)

In [88]:
df

,Year,first_prediction,second_prediction,third_prediction,actual,first_prediction_fn
0,2000,SEA,ATL,STL,NYY,New York Yankees
1,2009,LAA,STL,FLA,NYY,New York Yankees
2,2001,SEA,CHC,CLE,ARI,Arizona Diamondbacks
3,2002,ANA,NYY,BOS,ANA,Anahiem Angels
4,2003,SFG,HOU,TOR,FLA,Florida Marlins
5,2004,BOS,STL,SFG,BOS,Boston Red Sox
6,2007,SEA,COL,DET,BOS,Boston Red Sox
7,2013,STL,BOS,CIN,BOS,Boston Red Sox
8,2018,BOS,CLE,COL,BOS,Boston Red Sox
9,2005,OAK,ATL,STL,CHW,Chicago White Sox
10,2006,NYM,MIN,LAA,STL,St. Louis Cardinals
11,2011,ARI,MIL,DET,STL,St. Louis Cardinals
12,2008,BOS,LAA,NYM,PHI,Philadelphia Phillies
13,2010,MIN,NYY,TEX,SFG,San Francisco Giants
14,2012,TEX,DET,NYY,SFG,San Francisco Giants
15,2014,DET,TOR,LAD,SFG,San Francisco Giants
16,2015,TOR,KCR,SFG,KCR,Kansas City Royals
17,2016,BOS,CLE,SEA,CHC,Chicago Cubs
18,2017,HOU,CLE,LAD,HOU,Houston Astros
19,2019,WSN,LAD,HOU,WSN,Washington Nationals
20,2020,LAD,TBR,OAK,LAD,Los Angeles Dodgers

In [81]:
df.to_json('nn_predictions.json')